### ISSUE TITLE
Vue Cli Error on starting dev server

### ISSUE THREAD

**Issue by canperk** [DaniJG/ASPCoreVueCLITemplates#1]
I have applied all steps and then i am getting the error :

ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number

**Comment by DaniJG** [comment]
Hi @canperk from which exact template where you running it and from which project?

If you could copy the full command and its output that would be great. (I would suggest to double check the npm command was run from the right folder where the frontend lives)

**Comment by canperk** [comment]
Hi @DaniJG !!

I consider that my project structure is not suitable for the middleware options. Hence i will copy here the file structure for your info. In addtion for your question, i am using adapted one 

![image](https://user-images.githubusercontent.com/17784391/62123425-9092eb00-b2d0-11e9-97b2-9d2cb5ccd6ef.png)

**Comment by DaniJG** [comment]
What command are you trying to run? Is it `npm run serve` from within that CevSis.SuKalite.Web project?

**Comment by canperk** [comment]
I have seperated the projects to resolve the issue. Thanks
