### ISSUE TITLE
how to UseStaticFiles 

### ISSUE THREAD

**Issue by godshades** [DaniJG/ASPCoreVueCLITemplates#6]
Hi, thanks for your template, I'm using "alternative-spa-template"
In my project, I have folder "Test"
when I access with default link: http://localhost:3797/Test => not work
but with asp server link: http://localhost:5001/Test => OK

How I can make it work with default link ?

**Comment by DaniJG** [comment]
Hi @godshades could you provide some additional details? 

- What do you mean by folder "Test"? Is that a controller you added to the ASP.NET Core side? Whats the ASP.NET Core route for it?
- How do you make that request? Are you simply opening it on the browser, because if so note that the webpack-dev-server proxy would only work for ajax requests once the app has initially loaded 
- Have you noticed any errors in the browser console? 
- What do you exactly mean by "not work"? A 404 response? A 500 response?

**Comment by godshades** [comment]
@DaniJG 

- Yes this folder is in ASP server side and I don't have router for it. I'm using router.js for vue only (Sorry I'm newbie)

- This folder contain pdf file, in my page, I just click to link to view pdf file  https://localhost:5001/Test /test.pdf

- When go to  http://localhost:3797/Test/test.pdf It just return 404 and no error

I explain more about this
Before I put folder Test inside "ClientApp\public" folder
And I have funtion to upload pdf file to this folder
But when update to this folder => webpack will force refresh my page because public folder change
So I put it in same ASP server root then use UseStaticFiles to link to this folder

*Sorry for bad english :D

**Comment by DaniJG** [comment]
Got it. I think the main issue is that the webpack development server used for the Vue CLI will only proxy by default AJAX requests (ie, the requests that the browser makes _after_ the application is bootstrapped in the browser)

See the warning in this section of the Vue CLI documentation: https://cli.vuejs.org/config/#devserver-proxy

So what you can do is to update the `devServer.proxy` section inside the `vue.config.js` file. You will need to provide more granular control over which routes get passed down to the ASP.NET Core server.

Here is an example of a modified `vue.config.js` file that will proxy all requests for `/api` and `/Test` paths:
```js
module.exports = {
  devServer: {
    // Use fine granined control over what requests get proxied by the webpack dev server and sent to the underlying ASP.NET Core server
    // Otherwise, only AJAX requests are proxiesd. See:
    //   https://cli.vuejs.org/config/#devserver-proxy
    //   https://github.com/chimurai/http-proxy-middleware
    proxy: {
      '^/api': {
        // The URL where the .Net Core app will be listening.
        //    See https://cli.vuejs.org/config/#devserver-proxy and https://webpack.js.org/configuration/dev-server#devserverproxy
        // Instead of hardcoding something lile https://localhost:5001/,
        // read the ASPNET_URL environment variable, injected by VueDevelopmentServerMiddleware
        target: process.env.ASPNET_URL || 'https://localhost:44345',
      },
      '^/Test': {
        target: process.env.ASPNET_URL || 'https://localhost:44345',
      }
    }
  },
  configureWebpack: {
    // Use source map for debugging in VS and VS Code
    devtool: 'source-map',
    // Breakpoints in VS and VSCode wont work since the source maps conside clien-app the project root, rather than its parent folder
    output: {
      devtoolModuleFilenameTemplate: info => {
        const resourcePath = info.resourcePath.replace('./src', './ClientApp/src')
        return `webpack:///${resourcePath}?${info.loaders}`
      }
    }
  }
}

```

**Comment by DaniJG** [comment]
@godshades let me know if that helps and I will hopefully close the issue!

**Comment by godshades** [comment]
@DaniJG thanks so much, it's work
